name: github_actions_test

on:
  push:
    branches:
      - master
  schedule: 
    - cron: '0 */4 * * *'  # This will run the workflow every 4 hours

jobs:
  modify-sample-app:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Modify the sample app
      run: |
        cp -r ./__tests__/dotnetsampleapp dotnetapp
        current_utc_time=$(date -u +"%Y-%m-%d %H:%M:%S %Z")
        sed -i "s/<<<net-place-holder>>>/$current_utc_time/g" dotnetapp/Controllers/HelloController.cs

        echo "The placeholder has been replaced with the current UTC time: $current_utc_time"

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Build with dotnet
      run: dotnet build --configuration Release dotnetapp/DOTNET_8_APP.csproj

    - name: dotnet publish
      run: dotnet publish dotnetapp/DOTNET_8_APP.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: .net-app
        path: ${{env.DOTNET_ROOT}}/myapp
  
  deploy:
    runs-on: ubuntu-latest
    needs: modify-sample-app
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'dotnetsampleapp8'
          slot-name: 'Production'
          package: .